[2021-01-22 10:47:37,965] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:47:34.823043+00:00 [queued]>
[2021-01-22 10:47:37,969] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:47:34.823043+00:00 [queued]>
[2021-01-22 10:47:37,969] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 10:47:37,969] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-22 10:47:37,969] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 10:47:37,974] {taskinstance.py:1038} INFO - Executing <Task(DataQualityOperator): Data_Quality_Check_for_Low_Income_table> on 2021-01-22T15:47:34.823043+00:00
[2021-01-22 10:47:37,977] {standard_task_runner.py:51} INFO - Started process 46677 to run task
[2021-01-22 10:47:37,983] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'low_income_hospitals', 'Data_Quality_Check_for_Low_Income_table', '2021-01-22T15:47:34.823043+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/low_income_hospitals.py', '--cfg-path', '/var/folders/yg/z5092h4j73z95n7zhxq2kwx1szwm14/T/tmp7errspp9']
[2021-01-22 10:47:37,985] {standard_task_runner.py:76} INFO - Job 78: Subtask Data_Quality_Check_for_Low_Income_table
[2021-01-22 10:47:38,012] {logging_mixin.py:103} INFO - Running <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:47:34.823043+00:00 [running]> on host shs-l5320.ssp.pri
[2021-01-22 10:47:38,032] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=zawnaingwynn@gmail.com
AIRFLOW_CTX_DAG_OWNER=Harry
AIRFLOW_CTX_DAG_ID=low_income_hospitals
AIRFLOW_CTX_TASK_ID=Data_Quality_Check_for_Low_Income_table
AIRFLOW_CTX_EXECUTION_DATE=2021-01-22T15:47:34.823043+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-22T15:47:34.823043+00:00
[2021-01-22 10:47:38,037] {base.py:74} INFO - Using connection to: id: redshift. Host: zipcoderedshift.cvh0gkrokjip.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: zipcode, Login: harry, Password: XXXXXXXX, extra: None
[2021-01-22 10:47:38,745] {dbapi.py:180} INFO - Running statement: Select count(*) from public.low_income_area;, parameters: None
[2021-01-22 10:47:38,926] {dbapi.py:186} INFO - Rows affected: 1
[2021-01-22 10:47:39,017] {taskinstance.py:1396} ERROR - 'DataQualityOperator' object has no attribute 'hook'
Traceback (most recent call last):
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/zwin/Desktop/airflow/plugins/operators/data_quality.py", line 30, in execute
    for output in self.hook.conn.notices:
AttributeError: 'DataQualityOperator' object has no attribute 'hook'
[2021-01-22 10:47:39,021] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=low_income_hospitals, task_id=Data_Quality_Check_for_Low_Income_table, execution_date=20210122T154734, start_date=20210122T154737, end_date=20210122T154739
[2021-01-22 10:47:39,056] {local_task_job.py:118} INFO - Task exited with return code 1
